name: Nightly Build

on:
  schedule:  # UTC at 0300 - 11pm EDT
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'ansys-tools-omniverse'
  ENSIGHT_IMAGE: 'ghcr.io/ansys-internal/ensight_dev'

jobs:
  nightly_build:
    name: Nightly build
    runs-on: ubuntu-latest
    steps:

      - name: Build library source and wheel artifacts
        uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Upload wheel
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: ansys-pyensight-wheel
          path: dist/
          retention-days: 7
          if-no-files-found: error

      # Upload a renamed wheel to the private Azure PyPi for nightly consumption
      # in EnSight
      - name: Upload to Ansys Azure PyPi
        if: ${{ !env.ACT }}
        run: |
          python rename_nightly_wheel.py
          twine upload --verbose dist/*.whl
        env:
          TWINE_USERNAME: PAT
          TWINE_PASSWORD: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
          TWINE_REPOSITORY_URL: ${{ secrets.PRIVATE_PYPI_URL }}


